# Generated by Django 4.2.30 on 2026-04-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('migration_app', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('cheque', 'Cheque'), ('adjustment', 'Adjustment')], default='bank', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='masters.party')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='migration_app.migrationbatch')),
            ],
            options={
                'ordering': ['payment_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_date', models.DateField()),
                ('balance_type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], default='DR', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='masters.party')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='migration_app.migrationbatch')),
            ],
            options={
                'ordering': ['effective_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='masters.party')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='migration_app.migrationbatch')),
            ],
            options={
                'ordering': ['invoice_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_number', ''), _negated=True), fields=('party', 'reference_number'), name='uniq_party_payment_reference'),
        ),
        migrations.AddConstraint(
            model_name='openingbalance',
            constraint=models.UniqueConstraint(fields=('party', 'effective_date', 'balance_type', 'amount'), name='uniq_opening_balance_signature'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number', ''), _negated=True), fields=('party', 'invoice_number'), name='uniq_party_invoice_number'),
        ),
    ]
