# Generated by Django 4.2.30 on 2026-04-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_portal_receipt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='inspection_report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoice_reports/inspection/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='part_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='process_report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoice_reports/process/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
