# Generated by Django 4.2.30 on 2026-04-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_invoice_inspection_part_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="part_name",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="report_date",
        ),
    ]
