# Generated by Django 4.2.30 on 2026-04-19 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=255)),
                ('upload', models.FileField(upload_to='imports/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('imported', 'Imported'), ('failed', 'Failed')], default='preview', max_length=20)),
                ('import_type', models.CharField(choices=[('parties', 'Parties'), ('opening_balances', 'Opening Balances'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('challans', 'Challans')], max_length=30)),
                ('file_type', models.CharField(choices=[('xlsx', 'XLSX'), ('csv', 'CSV')], default='xlsx', max_length=10)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MigrationRowError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('sheet_name', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField(default=dict)),
                ('error_message', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='migration_app.migrationbatch')),
            ],
            options={
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MigrationMappingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('parties', 'Parties'), ('opening_balances', 'Opening Balances'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('challans', 'Challans')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('column_mapping_config', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['import_type', 'name'],
                'unique_together': {('import_type', 'name')},
            },
        ),
    ]
