# Generated by Django 4.2.30 on 2026-04-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationbatch',
            name='import_type',
            field=models.CharField(choices=[('parties', 'Parties'), ('opening_balances', 'Opening Balances'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('challans', 'Challans'), ('production_dashboard_workbook', 'Production Dashboard Workbook')], max_length=30),
        ),
        migrations.AlterField(
            model_name='migrationmappingprofile',
            name='import_type',
            field=models.CharField(choices=[('parties', 'Parties'), ('opening_balances', 'Opening Balances'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('challans', 'Challans'), ('production_dashboard_workbook', 'Production Dashboard Workbook')], max_length=30),
        ),
    ]
