# Generated by Django 4.2.30 on 2026-04-19 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('migration_app', '0002_alter_migrationbatch_import_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationbatch',
            name='rollback_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='migrationbatch',
            name='rolled_back_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationbatch',
            name='rolled_back_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolled_back_migration_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='migrationbatch',
            name='status',
            field=models.CharField(choices=[('preview', 'Preview'), ('imported', 'Imported'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='preview', max_length=20),
        ),
    ]
