# Generated by Django 4.2.30 on 2026-04-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('migration_app', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(blank=True, max_length=100)),
                ('challan_date', models.DateField()),
                ('job_description', models.CharField(max_length=255)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN', max_length=3)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challans', to='masters.party')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_challans', to='migration_app.migrationbatch')),
            ],
            options={
                'ordering': ['-challan_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='challan',
            constraint=models.UniqueConstraint(condition=models.Q(('challan_number', ''), _negated=True), fields=('party', 'challan_number'), name='uniq_party_challan_number'),
        ),
    ]
