# Generated by Django 4.2.30 on 2026-04-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='receipt_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
