# Generated by Django 4.2.30 on 2026-04-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_processreport_inspectionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='processreport',
            name='inspection_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_report', to='production.inspectionreport'),
        ),
    ]
